if [ -f $HOME/.shell_local_before ]; then
    source $HOME/.shell_local_before
fi

if [ -f $HOME/.zshrc_local_before ]; then
    source $HOME/.zshrc_local_before
fi

source $HOME/.shell/functions.sh
source $HOME/.shell/bootstrap.sh
source $HOME/.zsh/settings.zsh
source $HOME/.zsh/plugins.zsh
source $HOME/.shell/external.sh

if [ -f $HOME/.shell_local_after ]; then
    source $HOME/.shell_local_after
fi

if [ -f ~/.zshrc_local_after ]; then
    source ~/.zshrc_local_after
fi

# >>> mamba initialize >>>
# !! Contents within this block are managed by 'mamba init' !!
export MAMBA_EXE='/opt/homebrew/opt/micromamba/bin/micromamba';
export MAMBA_ROOT_PREFIX='/Users/yutai/micromamba';
__mamba_setup="$("$MAMBA_EXE" shell hook --shell zsh --root-prefix "$MAMBA_ROOT_PREFIX" 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__mamba_setup"
else
    alias micromamba="$MAMBA_EXE"  # Fallback on help from mamba activate
fi
unset __mamba_setup
# <<< mamba initialize <<<

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/yutai/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/yutai/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/yutai/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/yutai/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# path=('/Users/yutai/mambaforge/bin' $path) # managed by mamba
# path=('/opt/homebrew/bin' $path)
# path=('/opt/homebrew/sbin' $path)
# path=('/Users/yutai/.local/bin' $path) # bootstrap
# path=('/Users/yutai/bin' $path) # bootstrap
# path=('/bin' $path) # already there?
export PATH

# export PATH="PATH:/bin"
# export PATH="PATH:$HOME/bin"
# fpath+=~/.zfunc; autoload -Uz compinit; compinit

# zstyle ':completion:*' menu select
source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
