if [ -f $HOME/.shell_local_before ]; then
    source $HOME/.shell_local_before
fi

if [ -f $HOME/.bashrc_local_before ]; then
    source $HOME/.bashrc_local_before
fi

source $HOME/.shell/functions.sh
source $HOME/.shell/bootstrap.sh
source $HOME/.bash/settings.bash
source $HOME/.bash/plugins.bash
source $HOME/.shell/external.sh

if [ -f $HOME/.shell_local_after ]; then
    source $HOME/.shell_local_after
fi

if [ -f $HOME/.bashrc_local_after ]; then
    source $HOME/.bashrc_local_after
fi
