source $HOME/.shell/functions.sh

# Allow local customizations in the $HOME/.shell_local_before file
if [ -f $HOME/.shell_local_before ]; then
    source $HOME/.shell_local_before
fi

# Allow local customizations in the $HOME/.bashrc_local_before file
if [ -f $HOME/.bashrc_local_before ]; then
    source $HOME/.bashrc_local_before
fi

source $HOME/.shell/bootstrap.sh
source $HOME/.bash/settings.bash
source $HOME/.bash/plugins.bash

# Allow local customizations in the $HOME/.shell_local_after file
if [ -f $HOME/.shell_local_after ]; then
    source $HOME/.shell_local_after
fi

# Allow local customizations in the $HOME/.bashrc_local_after file
if [ -f $HOME/.bashrc_local_after ]; then
    source $HOME/.bashrc_local_after
fi

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/yutai/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/yutai/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/yutai/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/yutai/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<


